    LIST 	P=16F877A
    INCLUDE	P16F877.INC
    __CONFIG _CP_OFF &_WDT_OFF & _BODEN_ON & _PWRTE_ON & _XT_OSC & _WRT_ENABLE_OFF & _LVP_OFF & _DEBUG_OFF & _CPD_OFF

    org 0x00
    
    BSF	    STATUS, RP0	    ; SELECT BANK1
    
    MOVLW   0x38
    MOVWF   TRISB	    ; BUTTONS 3, 4, 5, INPUT MODE
    
    CLRF    TRISA	    ; PORTA, OUTPUT MODE
    CLRF    TRISD	    ; PORTD, OUTPUT MODE
    
    BCF	    STATUS, RP0	    ; SELECT BANK0
    CLRF    PORTA
    CLRF    PORTD
    
    BSF	    PORTA, 5	    ; SELECT 4TH SSD FROM LEFT
    
COUNTER	    EQU	    0x20
I	    EQU	    0x21
J	    EQU	    0x22
    
    CLRF    COUNTER	; COUNTER = 0
MAIN
    BTFSS   PORTB, 3
    GOTO    BUTTON3PRESSED
    
    BTFSS   PORTB, 4
    GOTO    BUTTON4PRESSED
    
    BTFSS   PORTB, 5
    GOTO    BUTTON5PRESSED
    
DISPLAY
    MOVFW   COUNTER	; WREG = COUNTER
    CALL    GETCODE	; WREG = BINARY CODE
    MOVWF   PORTD
; DISPLAY, END  
    
    CALL    ISANYBUTTONPRESSED
    GOTO    MAIN
    
; MAIN, END

    
ISANYBUTTONPRESSED:
    CALL    DELAY
    RETURN
; ISANYBUTTONPRESSED, END
    
    
BUTTON3PRESSED
    MOVLW   d'9'
    SUBWF   COUNTER, W	; WREG = COUNTER - 9
    BTFSS   STATUS, Z	; skip next if COUNTER == 9
    GOTO    INCREMENT
    
    CLRF    COUNTER	; COUNTER = 0
    GOTO    DISPLAY
    
INCREMENT
    INCF    COUNTER, F  ; COUNTER += 1
    GOTO    DISPLAY
; BUTTON3PRESSED, END

BUTTON4PRESSED
    MOVFW   COUNTER	; WREG = COUNTER
    BTFSS   STATUS, Z	; skip next if COUNTER != 0
    GOTO    DECREMENT
    MOVLW   d'9'
    MOVWF   COUNTER	; COUNTER = 9
    GOTO    DISPLAY
    
DECREMENT
    DECF    COUNTER, F	; COUNTER -= 1
    GOTO    DISPLAY
; BUTTON4PRESSED, END
    
BUTTON5PRESSED
    CLRF    COUNTER	; COUNTER = 0
    GOTO    DISPLAY
; BUTTON5PRESSED, END
    
    
GETCODE:
    ADDWF   PCL, F  ; PROGRAM COUNTER REGISTER += WREG
    RETLW   B'00111111'		; 0
    RETLW   B'00000110'		; 1
    RETLW   B'01011011'		; 2
    RETLW   B'01001111'		; 3
    RETLW   B'01100110'		; 4
    RETLW   B'01101101'		; 5
    RETLW   B'01111101'		; 6
    RETLW   B'00000111'		; 7
    RETLW   B'01111111'		; 8
    RETLW   B'01101111'		; 9  

    
DELAY:
    MOVLW   d'100'
    MOVWF   I			   
DELAY_OUTERLOOP
    MOVLW   d'250'
    MOVWF   J			    
DELAY_INNERLOOP	
    NOP
    DECFSZ  J, F		   
    GOTO    DELAY_INNERLOOP

    DECFSZ  I, F		    
    GOTO    DELAY_OUTERLOOP
    RETURN
	
FINISH_BLOCK
LOOP    GOTO $
     END
     